/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import connections.APIconnection;
import controllers.FavoriteListJpaController;
import controllers.GenreJpaController;
import controllers.MovieJpaController;
import controllers.exceptions.NonexistentEntityException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import models.FavoriteList;
import models.Genre;
import models.Movie;

/**
 *
 * @author elena
 */
public class MainMenuApp extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuApp
     */
    public MainMenuApp() {
        initComponents();
        this.emf = Persistence.createEntityManagerFactory("myMovies_testPU");
        this.jpListmanage.setVisible(false);
        this.jpSearchMovies.setVisible(false);
        this.jpStart.setVisible(true);
        this.bindFavoriteList();
        this.bindGenreComboBox();
        this.bindFaforiteListComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfLoading = new javax.swing.JFrame();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jfCreateList = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jtfNewName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnCreateList = new javax.swing.JButton();
        btnCreateCancel = new javax.swing.JButton();
        jfEditList = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jtfChangeName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnEditList = new javax.swing.JButton();
        btnEditCancel = new javax.swing.JButton();
        jfDeleteValidation = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnDeleteYes = new javax.swing.JButton();
        btnDeleteCancel = new javax.swing.JButton();
        jlDeletingList = new javax.swing.JLabel();
        jpButtons = new javax.swing.JPanel();
        btnManageLists = new javax.swing.JButton();
        btnDiscoverMovies = new javax.swing.JButton();
        btnMoviesStatistics = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnGetMovies = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jpSearchMovies = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jcbGenre = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        btnSearchMovies = new javax.swing.JButton();
        btnClearCriteria = new javax.swing.JButton();
        jpTableMovies = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMoviesFind = new javax.swing.JTable();
        jcbFavoriteListSelection = new javax.swing.JComboBox();
        btnDeleteFromList = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtfselectedYear = new javax.swing.JTextField();
        labelNoCriteria = new javax.swing.JLabel();
        jpListmanage = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlFavoriteList = new javax.swing.JList();
        btnShowCreateList = new javax.swing.JButton();
        btnShowEditList = new javax.swing.JButton();
        btnShowDeleteValidation = new javax.swing.JButton();
        jpTableMoviesInList = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMoviesInList = new javax.swing.JTable();
        jpStart = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jpStatistika = new javax.swing.JPanel();

        jfLoading.setTitle("Loading");
        jfLoading.setMinimumSize(new java.awt.Dimension(450, 200));
        jfLoading.setUndecorated(true);

        jLabel10.setText("Η αποθήκευση των ταινιών στη βάση δεδομένων");

        jLabel11.setText("Ολοκληρωθηκε με επιτυχία!!");

        jButton1.setText("ΟΚ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jfLoadingLayout = new javax.swing.GroupLayout(jfLoading.getContentPane());
        jfLoading.getContentPane().setLayout(jfLoadingLayout);
        jfLoadingLayout.setHorizontalGroup(
            jfLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfLoadingLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jfLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jfLoadingLayout.setVerticalGroup(
            jfLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfLoadingLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel10)
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jfCreateList.setTitle("Δημιουργία Λίστας");
        jfCreateList.setMinimumSize(new java.awt.Dimension(320, 182));

        jPanel1.setToolTipText("");
        jPanel1.setMinimumSize(new java.awt.Dimension(290, 182));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Όνομα νέας Λίστας");

        btnCreateList.setText("Δημιουργία");
        btnCreateList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateListActionPerformed(evt);
            }
        });

        btnCreateCancel.setText("Ακύρωση");
        btnCreateCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnCreateList)
                .addGap(46, 46, 46)
                .addComponent(btnCreateCancel)
                .addGap(0, 56, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jtfNewName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jtfNewName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateList)
                    .addComponent(btnCreateCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jfCreateListLayout = new javax.swing.GroupLayout(jfCreateList.getContentPane());
        jfCreateList.getContentPane().setLayout(jfCreateListLayout);
        jfCreateListLayout.setHorizontalGroup(
            jfCreateListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfCreateListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jfCreateListLayout.setVerticalGroup(
            jfCreateListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfCreateListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jfEditList.setTitle("Δημιουργία Λίστας");
        jfEditList.setMinimumSize(new java.awt.Dimension(320, 182));

        jPanel2.setToolTipText("");
        jPanel2.setMinimumSize(new java.awt.Dimension(290, 182));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Νέο όνομα Λίστας");

        btnEditList.setText("Επεξεργασία");
        btnEditList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditListActionPerformed(evt);
            }
        });

        btnEditCancel.setText("Ακύρωση");
        btnEditCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnEditList)
                .addGap(46, 46, 46)
                .addComponent(btnEditCancel)
                .addGap(0, 56, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jtfChangeName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jtfChangeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditList)
                    .addComponent(btnEditCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jfEditListLayout = new javax.swing.GroupLayout(jfEditList.getContentPane());
        jfEditList.getContentPane().setLayout(jfEditListLayout);
        jfEditListLayout.setHorizontalGroup(
            jfEditListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfEditListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jfEditListLayout.setVerticalGroup(
            jfEditListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfEditListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jfDeleteValidation.setTitle("Δημιουργία Λίστας");
        jfDeleteValidation.setMinimumSize(new java.awt.Dimension(320, 182));

        jPanel3.setToolTipText("");
        jPanel3.setMinimumSize(new java.awt.Dimension(290, 182));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Θέλετε να διαγραφεί η λίστα");

        btnDeleteYes.setText("Διαγραφή");
        btnDeleteYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteYesActionPerformed(evt);
            }
        });

        btnDeleteCancel.setText("Ακύρωση");
        btnDeleteCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCancelActionPerformed(evt);
            }
        });

        jlDeletingList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlDeletingList, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(btnDeleteYes)
                            .addGap(44, 44, 44)
                            .addComponent(btnDeleteCancel))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jLabel8))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jlDeletingList, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteYes)
                    .addComponent(btnDeleteCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jfDeleteValidationLayout = new javax.swing.GroupLayout(jfDeleteValidation.getContentPane());
        jfDeleteValidation.getContentPane().setLayout(jfDeleteValidationLayout);
        jfDeleteValidationLayout.setHorizontalGroup(
            jfDeleteValidationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfDeleteValidationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jfDeleteValidationLayout.setVerticalGroup(
            jfDeleteValidationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfDeleteValidationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("myMovies");
        setBackground(new java.awt.Color(124, 124, 172));

        jpButtons.setBackground(new java.awt.Color(109, 142, 242));

        btnManageLists.setBackground(new java.awt.Color(109, 142, 242));
        btnManageLists.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnManageLists.setForeground(new java.awt.Color(255, 255, 255));
        btnManageLists.setText("Διαχείριση Λιστών Αγαπημένων Ταινιών");
        btnManageLists.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 153, 255), null));
        btnManageLists.setContentAreaFilled(false);
        btnManageLists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageListsActionPerformed(evt);
            }
        });

        btnDiscoverMovies.setBackground(new java.awt.Color(109, 142, 242));
        btnDiscoverMovies.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnDiscoverMovies.setForeground(new java.awt.Color(255, 255, 255));
        btnDiscoverMovies.setText("Αναζήτηση Ταινιών");
        btnDiscoverMovies.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 153, 255), null));
        btnDiscoverMovies.setContentAreaFilled(false);
        btnDiscoverMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscoverMoviesActionPerformed(evt);
            }
        });

        btnMoviesStatistics.setBackground(new java.awt.Color(109, 142, 242));
        btnMoviesStatistics.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnMoviesStatistics.setForeground(new java.awt.Color(255, 255, 255));
        btnMoviesStatistics.setText("Στατιστικά");
        btnMoviesStatistics.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 153, 255), null));
        btnMoviesStatistics.setContentAreaFilled(false);
        btnMoviesStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoviesStatisticsActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(109, 142, 242));
        btnExit.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Έξοδος");
        btnExit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnExit.setContentAreaFilled(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnGetMovies.setBackground(new java.awt.Color(109, 142, 242));
        btnGetMovies.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnGetMovies.setForeground(new java.awt.Color(255, 255, 255));
        btnGetMovies.setText("Ανάκτηση και Αποθήκευση Δεδομένων Ταινιών ");
        btnGetMovies.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 153, 255), null));
        btnGetMovies.setContentAreaFilled(false);
        btnGetMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetMoviesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpButtonsLayout = new javax.swing.GroupLayout(jpButtons);
        jpButtons.setLayout(jpButtonsLayout);
        jpButtonsLayout.setHorizontalGroup(
            jpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpButtonsLayout.createSequentialGroup()
                .addGroup(jpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnExit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMoviesStatistics, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDiscoverMovies, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGetMovies, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageLists, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpButtonsLayout.setVerticalGroup(
            jpButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpButtonsLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(btnGetMovies, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnManageLists, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnDiscoverMovies, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnMoviesStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.setBackground(new java.awt.Color(167, 167, 255));

        jpSearchMovies.setBackground(new java.awt.Color(167, 167, 255));
        jpSearchMovies.setMinimumSize(new java.awt.Dimension(550, 530));

        jLabel4.setText("Είδος");

        jcbGenre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbGenre.setSelectedIndex(-1);

        jLabel9.setText("Έτος Κυκλοφορίας");

        btnSearchMovies.setText("Αναζήτηση");
        btnSearchMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchMoviesActionPerformed(evt);
            }
        });

        btnClearCriteria.setText("Καθαρισμός");
        btnClearCriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearCriteriaActionPerformed(evt);
            }
        });

        tblMoviesFind.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMoviesFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMoviesFindMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMoviesFind);

        jcbFavoriteListSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbFavoriteListSelection.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbFavoriteListSelectionItemStateChanged(evt);
            }
        });

        btnDeleteFromList.setText("Διαγραφή από Λίστα");
        btnDeleteFromList.setEnabled(false);
        btnDeleteFromList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFromListActionPerformed(evt);
            }
        });

        jLabel5.setText("Προσθήκη σε Λίστα");

        javax.swing.GroupLayout jpTableMoviesLayout = new javax.swing.GroupLayout(jpTableMovies);
        jpTableMovies.setLayout(jpTableMoviesLayout);
        jpTableMoviesLayout.setHorizontalGroup(
            jpTableMoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTableMoviesLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jpTableMoviesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpTableMoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jpTableMoviesLayout.createSequentialGroup()
                        .addComponent(jcbFavoriteListSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnDeleteFromList)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpTableMoviesLayout.setVerticalGroup(
            jpTableMoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTableMoviesLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTableMoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbFavoriteListSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteFromList))
                .addContainerGap())
        );

        labelNoCriteria.setText("   Παρακαλώ εισάγετε κριτήρια αναζήτησης");

        javax.swing.GroupLayout jpSearchMoviesLayout = new javax.swing.GroupLayout(jpSearchMovies);
        jpSearchMovies.setLayout(jpSearchMoviesLayout);
        jpSearchMoviesLayout.setHorizontalGroup(
            jpSearchMoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSearchMoviesLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btnSearchMovies, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClearCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(jpSearchMoviesLayout.createSequentialGroup()
                .addGroup(jpSearchMoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpSearchMoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpSearchMoviesLayout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(jcbGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtfselectedYear, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpSearchMoviesLayout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(jpTableMovies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpSearchMoviesLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(labelNoCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jpSearchMoviesLayout.setVerticalGroup(
            jpSearchMoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSearchMoviesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSearchMoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfselectedYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jcbGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(labelNoCriteria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jpSearchMoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchMovies)
                    .addComponent(btnClearCriteria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpTableMovies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpListmanage.setBackground(new java.awt.Color(167, 167, 255));
        jpListmanage.setMinimumSize(new java.awt.Dimension(550, 530));
        jpListmanage.setPreferredSize(new java.awt.Dimension(550, 530));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Διαχείρηση Λιστών");

        jScrollPane1.setMinimumSize(new java.awt.Dimension(180, 170));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(180, 170));

        jlFavoriteList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jlFavoriteList.setMaximumSize(new java.awt.Dimension(180, 170));
        jlFavoriteList.setMinimumSize(new java.awt.Dimension(180, 170));
        jlFavoriteList.setPreferredSize(new java.awt.Dimension(180, 170));
        jlFavoriteList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlFavoriteListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jlFavoriteList);

        btnShowCreateList.setText("Δημιουργία");
        btnShowCreateList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowCreateListActionPerformed(evt);
            }
        });

        btnShowEditList.setText("Επεξεργασία");
        btnShowEditList.setEnabled(false);
        btnShowEditList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowEditListActionPerformed(evt);
            }
        });

        btnShowDeleteValidation.setText("Διαγραφή");
        btnShowDeleteValidation.setEnabled(false);
        btnShowDeleteValidation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowDeleteValidationActionPerformed(evt);
            }
        });

        tblMoviesInList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblMoviesInList);

        javax.swing.GroupLayout jpTableMoviesInListLayout = new javax.swing.GroupLayout(jpTableMoviesInList);
        jpTableMoviesInList.setLayout(jpTableMoviesInListLayout);
        jpTableMoviesInListLayout.setHorizontalGroup(
            jpTableMoviesInListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTableMoviesInListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jpTableMoviesInListLayout.setVerticalGroup(
            jpTableMoviesInListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTableMoviesInListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpListmanageLayout = new javax.swing.GroupLayout(jpListmanage);
        jpListmanage.setLayout(jpListmanageLayout);
        jpListmanageLayout.setHorizontalGroup(
            jpListmanageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListmanageLayout.createSequentialGroup()
                .addGroup(jpListmanageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpListmanageLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpListmanageLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jpListmanageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpTableMoviesInList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpListmanageLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jpListmanageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnShowCreateList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnShowEditList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnShowDeleteValidation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jpListmanageLayout.setVerticalGroup(
            jpListmanageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpListmanageLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jpListmanageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpListmanageLayout.createSequentialGroup()
                        .addComponent(btnShowCreateList, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnShowEditList, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnShowDeleteValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addComponent(jpTableMoviesInList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpStart.setBackground(new java.awt.Color(167, 167, 255));
        jpStart.setMinimumSize(new java.awt.Dimension(550, 530));
        jpStart.setPreferredSize(new java.awt.Dimension(550, 530));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/popcorn.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 130));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mymovies.png"))); // NOI18N
        jLabel1.setText("Καλώς ήρθατε στο myMovies");

        jLabel3.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 130));
        jLabel3.setText("Φτιάξε Λιστες με τις Αγαπημενες σου Ταινίες");

        javax.swing.GroupLayout jpStartLayout = new javax.swing.GroupLayout(jpStart);
        jpStart.setLayout(jpStartLayout);
        jpStartLayout.setHorizontalGroup(
            jpStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpStartLayout.createSequentialGroup()
                .addGroup(jpStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpStartLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpStartLayout.createSequentialGroup()
                        .addContainerGap(38, Short.MAX_VALUE)
                        .addGroup(jpStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpStartLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(89, 89, 89)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jpStartLayout.setVerticalGroup(
            jpStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpStartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jpStatistika.setBackground(new java.awt.Color(167, 167, 255));
        jpStatistika.setMinimumSize(new java.awt.Dimension(550, 530));
        jpStatistika.setPreferredSize(new java.awt.Dimension(550, 530));

        javax.swing.GroupLayout jpStatistikaLayout = new javax.swing.GroupLayout(jpStatistika);
        jpStatistika.setLayout(jpStatistikaLayout);
        jpStatistikaLayout.setHorizontalGroup(
            jpStatistikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jpStatistikaLayout.setVerticalGroup(
            jpStatistikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpListmanage, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpStart, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(jpSearchMovies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 29, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(jpStatistika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 29, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jpListmanage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(jpSearchMovies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 34, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(jpStatistika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 34, Short.MAX_VALUE)))
        );
        jLayeredPane1.setLayer(jpSearchMovies, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jpListmanage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jpStart, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jpStatistika, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageListsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageListsActionPerformed
        // TODO add your handling code here:
        this.bindFavoriteList();
        this.jpListmanage.setVisible(true);
        this.jpStart.setVisible(false);
        this.jpSearchMovies.setVisible(false);
        this.jpTableMoviesInList.setVisible(false);
    }//GEN-LAST:event_btnManageListsActionPerformed

    private void btnDiscoverMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscoverMoviesActionPerformed
        // TODO add your handling code here:
        this.bindGenreComboBox();
        this.bindFaforiteListComboBox();
        this.jpSearchMovies.setVisible(true);
        this.jpListmanage.setVisible(false);
        this.jpStart.setVisible(false);
        this.jcbGenre.setSelectedIndex(-1); 
        this.jcbFavoriteListSelection.setSelectedIndex(-1);
        this.jtfselectedYear.setText(null);
        this.jpTableMovies.setVisible(false);
        this.labelNoCriteria.setVisible(false);
    }//GEN-LAST:event_btnDiscoverMoviesActionPerformed

    private void btnMoviesStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoviesStatisticsActionPerformed
        // TODO add your handling code here:
        this.jpStatistika.setVisible(true);
        this.jpStart.setVisible(false);
        this.jpListmanage.setVisible(false);
        this.jpSearchMovies.setVisible(false);
    }//GEN-LAST:event_btnMoviesStatisticsActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnGetMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetMoviesActionPerformed
        // TODO add your handling code here:
        this.jpStart.setVisible(true);
        this.jpListmanage.setVisible(false);
        this.jpSearchMovies.setVisible(false);
        
       
        APIconnection api = new APIconnection();
        api.clearMovies();
        try {  
            api.getGenres();
            api.getMovies();
        } catch (ParseException ex) {
            
        }
        
        this.jfLoading.setVisible(true);
        this.jfLoading.setLocationRelativeTo(null);
        
        
        
    }//GEN-LAST:event_btnGetMoviesActionPerformed

    private void btnShowCreateListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowCreateListActionPerformed
        // TODO add your handling code here:
        this.jfCreateList.setVisible(true);
        this.jfCreateList.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnShowCreateListActionPerformed

    private void btnCreateCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCancelActionPerformed
        // TODO add your handling code here:
        this.jfCreateList.setVisible(false);
    }//GEN-LAST:event_btnCreateCancelActionPerformed

    private void btnCreateListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateListActionPerformed
        // TODO add your handling code here:
        FavoriteList favList = new FavoriteList();
        favList.setName(this.jtfNewName.getText());
        
        FavoriteListJpaController fjc = new FavoriteListJpaController(this.emf);
        fjc.create(favList);
        this.jtfNewName.setText(null);
        this.bindFavoriteList();
        this.jfCreateList.setVisible(false);
        this.bindFaforiteListComboBox();
        this.btnShowDeleteValidation.setEnabled(false);
        this.btnShowEditList.setEnabled(false);
    }//GEN-LAST:event_btnCreateListActionPerformed

    private void btnEditListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditListActionPerformed
        // TODO add your handling code here:
        FavoriteListJpaController fjc = new FavoriteListJpaController(emf);
        FavoriteList favList = fjc.findFavoriteList(this.selectedListId);
        favList.setName(this.jtfChangeName.getText());
        try {
            fjc.edit(favList);
        } catch (Exception ex) {
            Logger.getLogger(MainMenuApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.bindFavoriteList();
        this.jtfChangeName.setText(null);
        this.jfEditList.setVisible(false);
        this.btnShowEditList.setEnabled(false);
        this.btnShowDeleteValidation.setEnabled(false);
        this.jlFavoriteList.clearSelection();
    }//GEN-LAST:event_btnEditListActionPerformed

    private void btnEditCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCancelActionPerformed
        // TODO add your handling code here:
        this.jtfChangeName.setText(null);
        this.jfEditList.setVisible(false);
        this.btnShowEditList.setEnabled(false);
        this.btnShowDeleteValidation.setEnabled(false);
        this.jlFavoriteList.clearSelection();
    }//GEN-LAST:event_btnEditCancelActionPerformed

    private void jlFavoriteListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlFavoriteListMouseClicked
        // TODO add your handling code here:
        this.btnShowEditList.setEnabled(true);
        FavoriteList favList = (FavoriteList) this.jlFavoriteList.getSelectedValue();
        this.selectedListId = favList.getId();
        this.btnShowDeleteValidation.setEnabled(true);
        this.bindTblList();
        this.jpTableMoviesInList.setVisible(true);
        
    }//GEN-LAST:event_jlFavoriteListMouseClicked

    private void btnShowEditListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowEditListActionPerformed
        // TODO add your handling code here:
        this.jfEditList.setVisible(true);
        this.jfEditList.setLocationRelativeTo(null);
        
        FavoriteListJpaController fjc = new FavoriteListJpaController(emf);
        FavoriteList favList = fjc.findFavoriteList(this.selectedListId);
        this.jtfChangeName.setText(favList.getName());
        
        
    }//GEN-LAST:event_btnShowEditListActionPerformed

    private void btnDeleteYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteYesActionPerformed
        // TODO add your handling code here:
        
        FavoriteListJpaController fjc = new FavoriteListJpaController(emf);
        try {
            fjc.destroy(this.selectedListId);
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(MainMenuApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.jfDeleteValidation.setVisible(false);
        this.bindFavoriteList();
        this.btnShowDeleteValidation.setEnabled(false);
        this.btnShowEditList.setEnabled(false);
        this.jlFavoriteList.clearSelection();
        this.jpTableMoviesInList.setVisible(false);
    }//GEN-LAST:event_btnDeleteYesActionPerformed

    private void btnDeleteCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCancelActionPerformed
        // TODO add your handling code here:
        this.btnShowEditList.setEnabled(false);
        this.jlFavoriteList.clearSelection();
        this.btnShowDeleteValidation.setEnabled(false);
        this.jfDeleteValidation.setVisible(false);
        
    }//GEN-LAST:event_btnDeleteCancelActionPerformed

    private void btnShowDeleteValidationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowDeleteValidationActionPerformed
        // TODO add your handling code here:
        this.jfDeleteValidation.setVisible(true);
        this.jfDeleteValidation.setLocationRelativeTo(null);
        
        FavoriteListJpaController fjc = new FavoriteListJpaController(emf);
        FavoriteList favList = fjc.findFavoriteList(this.selectedListId);
        this.jlDeletingList.setText(favList.getName());
        
        
    }//GEN-LAST:event_btnShowDeleteValidationActionPerformed

    private void btnSearchMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchMoviesActionPerformed
        // TODO add your handling code here:    
        if((this.jcbGenre.getSelectedIndex() == -1) || (this.jtfselectedYear.getText().isEmpty())){
            this.labelNoCriteria.setVisible(true);         
        }
        else{
            this.labelNoCriteria.setVisible(false);
            this.bindTblMoviesFind();
            this.jpTableMovies.setVisible(true);
        }                     
    }//GEN-LAST:event_btnSearchMoviesActionPerformed

    private void btnClearCriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearCriteriaActionPerformed
        // TODO add your handling code here:
        this.jcbGenre.setSelectedIndex(-1);
        this.jtfselectedYear.setText("");
        this.jpTableMovies.setVisible(false);
    }//GEN-LAST:event_btnClearCriteriaActionPerformed

    private void tblMoviesFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMoviesFindMouseClicked
        // TODO add your handling code here:
         this.jcbFavoriteListSelection.setSelectedIndex(-1);
        
        this.btnDeleteFromList.setEnabled(false);
        
        MovieJpaController controller = new MovieJpaController(emf);
       int selectedNum = this.tblMoviesFind.getSelectedRowCount();
       if (selectedNum == 1){
           int rowNum = this.tblMoviesFind.getSelectedRow();
          this.selectedMovieId = Integer.parseInt(this.tblMoviesFind.getValueAt(rowNum, 0).toString());
           Movie selectedMovie = controller.findMovie(selectedMovieId);
           
           if(selectedMovie.getFavoriteListId() == null){
               this.jcbFavoriteListSelection.setEnabled(true);
           }else {
               this.btnDeleteFromList.setEnabled(true);
               this.jcbFavoriteListSelection.setSelectedItem(selectedMovie.getFavoriteListId());
           }
           
       }
    }//GEN-LAST:event_tblMoviesFindMouseClicked

    private void btnDeleteFromListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFromListActionPerformed
        // TODO add your handling code here:
        MovieJpaController controller = new MovieJpaController(emf);
            Movie movie = controller.findMovie(this.selectedMovieId);
            movie.setFavoriteListId(null);
            try {
                controller.edit(movie);
            } catch (Exception ex) {
                Logger.getLogger(MainMenuApp.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.bindTblMoviesFind();
            this.btnDeleteFromList.setEnabled(false);
            this.jcbFavoriteListSelection.setSelectedIndex(-1);
    }//GEN-LAST:event_btnDeleteFromListActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.jfLoading.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcbFavoriteListSelectionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbFavoriteListSelectionItemStateChanged
        // TODO add your handling code here:
        
        if(this.jcbFavoriteListSelection.getSelectedIndex() == -1){
            
        }else {
            
            MovieJpaController controller = new MovieJpaController(emf);
            Movie movie = controller.findMovie(this.selectedMovieId);
            movie.setFavoriteListId((FavoriteList) this.jcbFavoriteListSelection.getSelectedItem());
            try {
                controller.edit(movie);
            } catch (Exception ex) {
                Logger.getLogger(MainMenuApp.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.bindTblMoviesFind();
                      
        }
    }//GEN-LAST:event_jcbFavoriteListSelectionItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuApp().setVisible(true);
                
            }
        });    
    }
    
    public void bindFavoriteList() {
        
        FavoriteListJpaController controller = new FavoriteListJpaController(emf);
        List<FavoriteList> favList = controller.findFavoriteListEntities();
        
        DefaultListModel model = new DefaultListModel();
        for (FavoriteList item : favList) {
            model.addElement(item);
        }   
        this.jlFavoriteList.setModel(model);
    }
    
    public void bindGenreComboBox(){

        GenreJpaController controller = new GenreJpaController(emf);
        List<Genre> genList = controller.findGenreEntities();
        
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for(Genre gen : genList){
            model.addElement(gen);
        }
        this.jcbGenre.setModel(model);
    }
    
    public void bindFaforiteListComboBox(){
    
        FavoriteListJpaController controller = new FavoriteListJpaController(emf);
        List<FavoriteList> favList = controller.findFavoriteListEntities();
        
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for(FavoriteList fav : favList){
            model.addElement(fav);
        }
        this.jcbFavoriteListSelection.setModel(model);  
    }
    
    public void bindTblMoviesFind(){
        MovieJpaController controller = new MovieJpaController(emf); 
        
        String year = this.jtfselectedYear.getText();
        String selectedGenre = this.jcbGenre.getSelectedItem().toString();
        
        String[] newIdentifiers = { "Id", "Τίτλος Ταινίας", "Βαθμολογία", "Περιγραφή" };
        List<Movie> movList = controller.findMovieByRelYear(year, selectedGenre);
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(newIdentifiers);
        
        for(Movie movie : movList){
            model.addRow(new String[] {
                movie.getId().toString(),
                movie.getTitle(),
                movie.getRating().toString(),
                movie.getOverview()
            });
        }
        this.tblMoviesFind.setModel(model);   
    }
    
    public void bindTblList(){
        FavoriteListJpaController listcontroller = new FavoriteListJpaController(emf);
        
        MovieJpaController controller = new MovieJpaController(emf);
        FavoriteList favList = listcontroller.findFavoriteList(this.selectedListId);
        List<Movie> movList = controller.findMovieByList(favList);
        
        String[] newIdentifiers = { "Id", "Τίτλος Ταινίας", "Βαθμολογία", "Περιγραφή" };
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(newIdentifiers);
        for(Movie movie : movList){
            model.addRow(new String[] {
                movie.getId().toString(),
                movie.getTitle(),
                movie.getRating().toString(),
                movie.getOverview()
            });
        }
        this.tblMoviesInList.setModel(model);
        //String listId = this.selectedListId.toString();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearCriteria;
    private javax.swing.JButton btnCreateCancel;
    private javax.swing.JButton btnCreateList;
    private javax.swing.JButton btnDeleteCancel;
    private javax.swing.JButton btnDeleteFromList;
    private javax.swing.JButton btnDeleteYes;
    private javax.swing.JButton btnDiscoverMovies;
    private javax.swing.JButton btnEditCancel;
    private javax.swing.JButton btnEditList;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGetMovies;
    private javax.swing.JButton btnManageLists;
    private javax.swing.JButton btnMoviesStatistics;
    private javax.swing.JButton btnSearchMovies;
    private javax.swing.JButton btnShowCreateList;
    private javax.swing.JButton btnShowDeleteValidation;
    private javax.swing.JButton btnShowEditList;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox jcbFavoriteListSelection;
    private javax.swing.JComboBox jcbGenre;
    private javax.swing.JFrame jfCreateList;
    private javax.swing.JFrame jfDeleteValidation;
    private javax.swing.JFrame jfEditList;
    private javax.swing.JFrame jfLoading;
    private javax.swing.JLabel jlDeletingList;
    private javax.swing.JList jlFavoriteList;
    private javax.swing.JPanel jpButtons;
    private javax.swing.JPanel jpListmanage;
    private javax.swing.JPanel jpSearchMovies;
    private javax.swing.JPanel jpStart;
    private javax.swing.JPanel jpStatistika;
    private javax.swing.JPanel jpTableMovies;
    private javax.swing.JPanel jpTableMoviesInList;
    private javax.swing.JTextField jtfChangeName;
    private javax.swing.JTextField jtfNewName;
    private javax.swing.JTextField jtfselectedYear;
    private javax.swing.JLabel labelNoCriteria;
    private javax.swing.JTable tblMoviesFind;
    private javax.swing.JTable tblMoviesInList;
    // End of variables declaration//GEN-END:variables
    int selectedListId;
    int selectedMovieId;
    EntityManagerFactory emf;
}
